# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "reseller-management"
client_id = "your-client-id"
application_url = "https://your-app-url.railway.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://your-app-url.railway.app/auth/callback",
  "https://your-app-url.railway.app/auth/shopify/callback",
  "https://your-app-url.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[[extensions]]
type = "admin_action"
name = "product_reseller_selector"
handle = "product-reseller-selector"

[extensions.targeting]
target = "admin.product-details.action"

[extensions.settings]
[[extensions.settings.fields]]
key = "api_url"
type = "single_line_text_field"
name = "Reseller API URL"
description = "The URL of your reseller management API"
default = "https://your-app-url.railway.app"