api_version = "2023-10"

[[extensions]]
type = "admin_action"
name = "product_reseller_field"

[[extensions.targeting]]
target = "admin.product-details.action"

[extensions.settings]
[[extensions.settings.fields]]
key = "api_url"
type = "single_line_text_field"
name = "Reseller API URL"
description = "The URL of your reseller management API"
default = "https://your-app-url.railway.app"
